unit8co/darts

- u8timeseries/tests/test_autoregression_models.py
- u8timeseries/tests/test_metrics.py
- u8timeseries/tests/test_missing_values.py
- u8timeseries/tests/test_regression_models.py
- u8timeseries/tests/test_statistics.py
- u8timeseries/tests/test_timeseries.py
- u8timeseries/tests/test_timeseries_generation.py
- u8timeseries/utils/timeseries_generation.py
- Created 6 different functions for the creation of TimeSeries objects.
- Included test cases for every function.
- Removed unnecessary lines of code from all test cases.
> Timeseries generation

- u8timeseries/timeseries.py
*args and **kwargs were not working when plotting
> make plot kwargs work again

- setup.py
Based on https://github.com/alkaline-ml/pmdarima/blob/master/setup.py
> Add more info about lib

- README.md
Round corners look nicer to me (and sync with the pypi badge). WDYT?
> Badge round corners

- .bumpversion.cfg
- conda_recipe/darts/meta.yaml
- darts/__init__.py
- docs/source/conf.py
- setup.py
This reverts commit b82b5109e19917342349b98d975ae2518de84a28.
> Revert "Release 0.1.0"

- darts/tests/test_RNN.py
- darts/tests/test_autoregression_models.py
Maybe it's worthwhile to introduce testcase class with common setups and cleanups?
> Cleanup after tests

- darts/timeseries.py
'freq' parameter of constructor now leads to overriding the automatic frequency detection in case of missing dates when passed
> hotfix/manual-frequency-override (#patch)

- darts/utils/statistics.py
Summary
* Cleaned and speeded up finding maxima of ACF
> clean check_seasonality function

- .bumpversion.cfg
- conda_recipe/darts/meta.yaml
- darts/__init__.py
- docs/source/conf.py
- setup.py
Fixes wrongful merge of master into develop (was part of an old release workflow) :/
> Revert "Release 0.3.0 (#205)"

- README.md
Fixes old ./gradlew syntax and typos.
> fix(readme): fixed ./gradlew syntax and typos

- .github/workflows/develop.yml
- .github/workflows/merge.yml
- .github/workflows/release.yml
- build.gradle
> fix(ci): merge pipeline now caches gradle download

- CONTRIBUTE.md
- README.md
I update the contribution guidelines with some development principles - let me know if you see anything missing.
> added contribution guidelines

- darts/datasets/__init__.py
Changed the paths in the datasets __init__.py to point to the current develop/datasets branch instead of feats/datasets/datasets branch. This branch and feats/datasets can be deleted after merging.
> Update path to datasets from feat/datasets to develop

- examples/01-darts-intro.ipynb
- examples/02-multi-time-series-and-covariates.ipynb
- examples/03-data-processing.ipynb
- examples/04-FFT-examples.ipynb
- examples/05-RNN-examples.ipynb
- examples/06-TCN-examples.ipynb
- examples/07-Transformer-examples.ipynb
- examples/08-NBEATS-examples.ipynb
Fix usage of datasets in notebooks.
> fix datasets usage in notebooks

- CHANGELOG.md
- README.md
Updated changelog and readme for 0.10.0
> Update changelog and Readme

- CHANGELOG.md
- README.md
https://pypi.org/project/codespell
Fixes #.
> Fix typos discovered by codespell

- darts/models/forecasting_model.py
- darts/tests/test_backtesting.py
> feat(gridsearch): added stride parameter support

- .github/workflows/develop.yml
- .github/workflows/merge.yml
- CHANGELOG.md
- CONTRIBUTE.md
- README.md
- darts/datasets/__init__.py
After merging this PR, the develop branch can be removed and replaced by the master branch.
> Replace mentions of develop branch by master

- README.md
Update README to reflect latest state of conda-forge package installation.
LightGBM information moved under PyPI section, as this should require no extra effort using the conda package.
> Update conda README

- README.md
- requirements/release.txt
Fixes #.
Since pmdarima 1.8.3, there are no more conflicts in the u8darts-all requirements and Python 3.9 is supported.
> Add conda Python 3.9 support to README

- darts/models/forecasting/exponential_smoothing.py
> Feat/added model parameters to ExponentialSmoothing.__str__() method

- darts/models/forecasting/forecasting_model.py
> feat(ForecastingModel): added call to fit method when model is untrained

- build.gradle
Fixes broken builds due to https://github.com/jazzband/pip-tools/issues/1558.
> Add workaround for broken pip-tools

- darts/tests/models/forecasting/test_ptl_trainer.py
fixes PyTorch-Lightning imports for flavoured tests
> fixed pytorch lightning import for flavor tests

- .pre-commit-config.yaml
- requirements/dev.txt
Fixes https://github.com/psf/black/issues/2964.
> Update black to 22.3.0

- darts/tests/datasets/test_dataset_loaders.py
> Change function name in tests

- CHANGELOG.md
I made a few mistakes in the changelog for those two PRs.
> fixed change log

- requirements/torch.txt
@gdevos010 could you have a quick look?
> Add torchmetric dependency

- darts/tests/models/forecasting/test_torch_forecasting_model.py
- requirements/torch.txt
Now this should (hopefully) fix it.
> resolve torchmetrics import issue

- .github/workflows/develop.yml
- examples/15-static-covariates.ipynb
attempt to fix failing tests for static covariates notebook
> fix static covariates notebook

- darts/tests/models/forecasting/test_transformer_model.py
Again fixing import for non torch flavors
> fix torch import for flavors

- darts/dataprocessing/dtw/dtw.py
- darts/models/forecasting/arima.py
- darts/models/forecasting/torch_forecasting_model.py
- darts/models/forecasting/varima.py
- darts/timeseries.py
Fixes #1177
logging.warn is deprecated
> logger.warn -> logger.warning

- darts/models/forecasting/gradient_boosted_model.py
While looking at Issue #1134 I noticed outdated comment [link](https://github.com/unit8co/darts/issues/1134#issuecomment-1301278323)
This pull request is ready to merge and makes no functional changes. Just fixes an outdated comment
> Fixes outdated comment about installing LightGBM

- CHANGELOG.md
- README.md
- darts/models/forecasting/dlinear.py
- darts/models/forecasting/nlinear.py
- darts/tests/models/forecasting/test_dlinear_nlinear.py
- docs/userguide/covariates.md
> DLinear and NLinear Documentation

- darts/models/forecasting/dlinear.py
- darts/models/forecasting/nlinear.py
- darts/tests/models/forecasting/test_dlinear_nlinear.py
Fixes https://github.com/unit8co/darts/issues/1393
@gdevos010 could you have a look at this one?
> fix issues with nlinear and dlinear future covariates

- docs/userguide/hyperparameter_optimization.md
Fixes #1556.
- references a proposed solution for PyTorchLightningPruningCallback error with pytorch-lightning>1.8.
> add note for fixing pruning callback issue

- darts/models/forecasting/regression_ensemble_model.py
Attempt to fix lint issue from previous PR.
> possible fix for lint issue

- build.gradle
Test PR to fix failing CI jobs due to pip error.
> remove pip<22

- docs/userguide/hyperparameter_optimization.md
- fixes typos in optuna example code
- fixes formatting in optuna example description
> fix typos in code and reformat description

- requirements/core.txt
Fixes current unit tests with holidays==0.25.0
> fix failing unit tests with holidays==0.25.0

- requirements/core.txt
Addresses #1772
- relaxes holidays version as prophet fixed the issue with holidays==0.25.0
> relax holidays version cap

- darts/utils/model_selection.py
Makes it a bit more consistent and corrects some spelling mistakes.
> Update docs of model_selection.py

- darts/explainability/__init__.py
- fixes torch import at core level requirements from `TFTExplainer`
> fix torch import on core requirements level

- examples/18-TiDE-examples.ipynb
Suggestions for improving the grammar in "~/examples/18-TiDE-examples.ipynb".
> improved grammar in the example notebook of TiDE

- darts/tests/models/forecasting/test_regression_ensemble_model.py
fixes failing unit tests from torch model import on core level
> remove torch import

- examples/19-EnsembleModel-examples.ipynb
Minor update to ensemble notebook's section for using historical forecasting to train the ensembl emodel
> udpate ensemble example notebook

- README.md
This puts a link to the DockerHub page to the exisiting badge in the README.
> Link docker profile in README.md

- pyproject.toml
- pytest.ini
Just minor enhancement
merge `pytest` config with the project config so there are ess files in root
> move pytest config to `pyproject.toml`

- darts/models/__init__.py
- fixes failing unit tests from torch import for core flavor
> fix torch baseline model import

- CHANGELOG.md
- requirements/release.txt
Fixes currently failing docs build unit tests.
- `lxml.html.clean` now has a dedicated package `lxml_html_clean` that we install
> lxml_html_clean for nbshinx

- darts/tests/models/forecasting/test_torch_forecasting_model.py
- fixes CI pipeline for no torch flavors due to torch import
> fix failing unit tests for no torch flavors

- darts/tests/models/forecasting/test_regression_ensemble_model.py
- fixes merge PR workflow for no torch flavor
> fix failing unit tests for no torch flavor

- .pre-commit-config.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- darts/ad/anomaly_model/anomaly_model.py
- darts/models/forecasting/forecasting_model.py
- darts/models/forecasting/pl_forecasting_module.py
- darts/models/forecasting/torch_forecasting_model.py
- darts/tests/models/forecasting/test_global_forecasting_models.py
- darts/tests/models/forecasting/test_local_forecasting_models.py
- darts/tests/models/forecasting/test_probabilistic_models.py
- darts/tests/utils/test_model_selection.py
- darts/timeseries.py
- darts/utils/data/horizon_based_dataset.py
- darts/utils/data/shifted_dataset.py
- darts/utils/statistics.py
- pyproject.toml
- requirements/dev.txt
Follow-up to #2323
`pyupgrade` functionality are fully covered with UP rule
> lint: replace `pyupgrade` with Ruff's rule UP

- docs/source/conf.py
- fixes docs build since __all__ module imports were introced in #2361
> remove docs __all__ imports

- darts/tests/test_timeseries.py
Fixes #2440.
In continuation of #2436.
Old versions of pandas were not taken into account when replacing applymap.
In older versions of pandas applymap is used, in new versions map.
> Uses applymap for older versions of pandas (for new ones map is used).

- CHANGELOG.md
- darts/ad/detectors/__init__.py
- darts/ad/detectors/iqr_detector.py
- darts/tests/ad/test_detectors.py
Closes #2319.
Added IQRDetector, allowing for detecting anomalies using the interquartile range algorithm.
It is based on the QuantileDetector and has a `scale` parameter for adjusting the acceptable range.
> Added the IQR Detector

- docs/userguide/torch_forecasting_models.md
Fixes #2454
No code change, only documentation
As of v0.30.0,  num_load was moved inside dataloader_kwargs. Reflect this change in documentation.
> Fix Issue 2454

- darts/metrics/metrics.py
Fixes #2480.
fixes docstring for `series_reduction` in metrics
> fix series_reduction docstring

- examples/21-TSMixer-examples.ipynb
> Fix typo in 21-TSMixer-examples.ipynb

- darts/tests/test_timeseries_static_covariates.py
Fixes currently failing unit tests
> attempt to fix failing test due to randomness

- CHANGELOG.md
- darts/ad/anomaly_model/anomaly_model.py
Fixes the comment of `scorers_are_univariate` in class `AnomalyModel`.
> Fix the comment of scorers_are_univariate

- .github/workflows/doc.yml
- .github/workflows/merge.yml
Part 2 to improve CI/CD pipeline:
- fixes failing merge workflow
> Update CI/CD pipelines Part 1

- .github/workflows/merge.yml
- fixes failing merge workflow part3
> Update CI/CD pipelines Part 2

- .github/workflows/develop.yml
- .github/workflows/update-cache.yml
- fixes failing macos checks where `uv` was not found after installation.
> add uv to path for mac pipeline

- darts/tests/models/forecasting/test_ensemble_models.py
Fixes failing unit tests on M1
> fix tests for m1

- darts/tests/models/forecasting/test_conformal_model.py
Fixes failing unit tests on M1 part 2
> fix tests for m1 part 2

- .github/workflows/develop.yml
- .github/workflows/merge.yml
- .github/workflows/update-cache.yml
- fixes failing update-cache workflow
> fixes failing update-cache workflow

- darts/tests/utils/test_timeseries_generation.py
Fixes failing tests from holidays release.
> fix failing tests from holidays release

- .github/codecov.yml
Ignore test files for code coverage.
> make codecov ignore test files

- CHANGELOG.md
- minor changelog fixes for release
> udpate changelog

- darts/tests/models/forecasting/test_regression_ensemble_model.py
- darts/tests/utils/historical_forecasts/test_historical_forecasts.py
Fixes all failing unit tests from #2894 for non-torch flavors.
> fix unit tests for non-torch flavors
