u8timeseries/custom_logging.py, u8timeseries/tests/test_autoregression_models.py, u8timeseries/tests/test_logging.py, u8timeseries/tests/test_metrics.py, u8timeseries/tests/test_timeseries.py
Removed all custom_logging messages from unittest output by
1. Suppressing logging in all unittest files where log messages are printed.
2. Redirect log messages to NullHandler() for test_logging.py (logging cannot be suppressed here since we test for the right logging messages).
=> fix(logging): removed all custom_logging messages from unittest output

.github/workflows/develop.yml, .gitignore, requirements/dev.txt
Fails if coverage <80%, currently 84%
These could use some tests:
Name                                                 Stmts   Miss  Cover   Missing
u8timeseries\backtesting\backtesting_udf.py             28     20    29%   37-60, 83-88
u8timeseries\backtesting\forecasting_simulation.py      52     40    23%   43-70, 97-131
u8timeseries\metrics\metrics.py                         80     34    58%   18-22, 44-47, 59-62, 74, 87-89, 101, 121, 135-141, 158-162, 165, 189, 208, 226
u8timeseries\models\statistics.py                       76     25    67%   38, 41, 59-60, 76, 90, 103, 137-138, 143, 176-180, 194-212
u8timeseries\utils\utils.py                             29     17    41%   22-28, 40-49, 52-55
...
---------------------------------------------------------------------------------- …
=> Add test coverage

.gitignore
when running the notebooks a folder `.darts` get populated with checkpoints and tensorboard logs that shouldn't be included in VCS.
=> add .darts to ignored folders

.github/workflows/merge.yml
Fixes DARTS-170
Change PR workflow so that all tests trigger on PR, and not after them.
This can prevent a failing develop branch.
PR created after discussion on #156
=> Fix PR workflow

.github/workflows/release.yml, build.gradle
Summary
* Refactored publishing docker image in release workflow
* Previously images were being published by github action
* Now they're published using gradle
Other Information
Workflow tested on mock repository in both possible cases (hotfix/non hotfix), but note that during tests different image (simple dockerfile) was being published on different repository (with different credentials).
=> Add publishing docker image by gradle in release workflow

.github/workflows/merge.yml, .github/workflows/release.yml
Changes the release workflow substantially.
Instead of triggering automatically on pushes to master and creating a draft release, the new release workflow is triggered manually (from the GitHub "Actions" tab in the repo) and requires to provide a "bump type" argument which must be one of `#major, #minor, #patch` (if something else is provided, the release is aborted without making any changes). There was no need for a draft release step anymore, so I removed it.
I also removed tests from the release workflow, and instead trigger the merge PR workflow on pushes to master.
To make a release, the new workflow is thus:
- Open a PR from develop to master.
- Merge PR (no need to put `#major`, … in the commit message anymore). This triggers the "darts merge PR workflow" which runs the full test …
=> Fix: Release workflow

README.md, requirements/dev-all.txt
Contribute guidelines were outdated since last release. The instruction to install pip packages references `main.txt` which does not exists anymore in place of `core.txt` and the other optional dependencies.
I did not find a way with pip to use something like `requirements/*.txt` so I added a file that has all the dependencies. Another way to fix it would have been to list all dependencies in the pip command (an updated version of the current instruction). Feel free to let me know if you prefer that approach
Another open question is if we want by default for the dev environment to also install the optional dependencies. I would expect it to be the case, so all the project tests can be run locally.
=> fix(readme): outdated instruction in contribute

CHANGELOG.md, darts/dataprocessing/pipeline.py
Adds a simple getter for `Pipeline._invertible` to allow writing `if pipeline.invertible(): …` (cleaner than accessing `_invertible` from outside the `Pipeline` class)
=> feat(pipeline): getter for Pipeline._invertible

darts/models/forecasting_model.py, darts/models/theta.py, darts/models/torch_forecasting_model.py, darts/tests/test_local_forecasting_models.py
I combined a few small things in this PR. For one, I tried to make the documentation of the `GlobalForecastingModel` class clearer. I also made some tweaks to the fit functions. ForecastingModel instances that are not extended are now only accepting univariate data.
=> [WIP] Fix/ForecastingModel and subclasses tweaks

darts/models/rnn_model.py, darts/tests/test_block_RNN.py
Quickie:  For some reason I removed the option to have more than one layer in the rnn module in the new `RNNModel` class. I simply reintroduced the parameter.
I also took care of some renaming that slipped past my attention.
=> Fix/ reintroduced n_rnn_layers parameter in RNNModel

darts/tests/test_block_RNN.py
Fixes skipping of BlockRNN tests (see test logs).
=> Fix import preventing BlockRNN tests from running

darts/models/rnn_model.py, darts/models/torch_forecasting_model.py, darts/tests/test_probabilistic_rnn.py, darts/utils/torch.py
I added `random_state` support to the appropriate methods invoked by `RNNModel` when instantiated with a likelihood model so that, while if the model produces `n` predictions they will all be pseudorandomly different from each other, if the same model is instantiated with the same `random_state` parameter, it will again produce the same `n` predictions.
=> Feat/added random_state support to DeepAR predictions

darts/models/torch_forecasting_model.py
Reverts unit8co/darts#388
mistakenly merged to master instead of develop
=> Revert "torch model exception on cuda 'Tensor for argument #2 'mat1' is on CP…"

darts/tests/test_regression_models.py
make test backward compatible with python 3.7
=> Fix failing test for python 3.7

darts/models/tcn_model.py
Fixes #470. Add the 1x1 convolution in a case of different number of channels between input and output of a residual block
=> Remove extra convolutions in TCN

darts/models/theta.py, darts/tests/test_timeseries.py, darts/timeseries.py
Fixes DeprecationWarnings from #DARTS-372.
* Fixes non-Enum in containment checks
* Fixes instantiating empty pandas.Series without specified dtype
* Fixes evaluating NotImplemented in a boolean context (from python 3.9)
* DeprecationWarning "import imp" still remains. Comes from Cython package (they already fixed it, see https://github.com/cython/cython/commit/120a841e7afa1958e803517f007bb9fd37c921f7)
=> Fixed DeprecationWarnings from tests.

darts/timeseries.py
Fixes #498 
Fixes spelling mistake fix_missing_date -> fix_missing_dates.
=> fixed a spelling mistake for error with fill_missing_dates

.github/workflows/merge.yml
The `installPipLatest` task was installing all dependencies
=> Fix: do not install all packages for flavour tests

README.md, darts/models/forecasting/block_rnn_model.py, darts/models/forecasting/nbeats.py, darts/models/forecasting/rnn_model.py, darts/models/forecasting/tcn_model.py, darts/models/forecasting/tft_model.py, darts/models/forecasting/torch_forecasting_model.py, darts/models/forecasting/transformer_model.py, darts/tests/test_block_RNN.py, darts/tests/test_probabilistic_models.py, darts/tests/test_transformer_model.py, darts/utils/likelihood_models.py
This is a probabilistic version of N-BEATS. N-BEATS is more tricky than the other models to make it probabilistic, because of the way the forecasts are built internally.
The way I've done it is by changing the dimensionality of the tensors returned by the blocks, from `(target_length,)` to `(target_length, nr_params)`, and then reshaping everything correctly to have the parameters at the right place in the output tensors. It requires care, because the time dimension may already contain interleaved dimensions of multivariate series (as N-BEATS is all univariate internally), but I think this is a way to do it that respects the architectural benefits of N-BEATS. There might still be better ways to do it, though.
I've tested with multivariate series, and also with/without generic architecture …
=> A probabilistic version of NBEATS

darts/utils/utils.py
This is necessary to turn of seasonality or trend in the `ExponentialSmoothing` model
=> Feat/added 'None' option in ModelMode Enum

darts/dataprocessing/dtw/dtw.py, darts/dataprocessing/dtw/window.py, darts/datasets/dataset_loaders.py, darts/metrics/metrics.py, darts/models/__init__.py, darts/tests/models/forecasting/test_encoders.py, darts/tests/models/forecasting/test_ensemble_models.py, darts/tests/models/forecasting/test_global_forecasting_models.py, darts/tests/models/forecasting/test_local_forecasting_models.py, darts/tests/models/forecasting/test_probabilistic_models.py, darts/tests/models/forecasting/test_prophet.py, darts/tests/test_datasets.py, darts/utils/data/horizon_based_dataset.py, darts/utils/data/inference_dataset.py, darts/utils/data/sequential_dataset.py, darts/utils/data/shifted_dataset.py, darts/utils/data/training_dataset.py, darts/utils/data/utils.py, darts/utils/model_selection.py, darts/utils/statistics.py, darts/utils/timeseries_generation.py, darts/utils/torch.py, darts/utils/utils.py
We had some imports using relative paths. Sometimes those were wrong which was causing tests to be skipped. These changes increase coverage from 85% to 91%.
=> Change some relative imports into absolute

darts/models/forecasting/torch_forecasting_model.py
Addresses #707. This only adds limited support for `ReduceLROnPlateau` in the sense that it only takes the training loss as `metrics` argument to its `step()` method. To add, say, validation loss we would have to change a few more things since the lr_scheduler is called at every epoch of the training loop, whereas new validation losses are not necessarily computed everytime. I guess it's not worth spending too much time on this considering the new PTL refactoring.
=> Fix/support for ReduceLROnPlateau scheduler

darts/models/forecasting/ensemble_model.py, darts/tests/models/forecasting/test_ensemble_models.py
Addresses #724.
- instantiating ensemble models with fitted/trained forecasting model resulted in deepcopy error. 
- added check for untrained models with explanatory error message.
=> added check for untrained models for copying of model parameters

darts/models/forecasting/tft_model.py
Fixes #722, #730
- fixes TFTModel non contiguous error with `lstm_layers > 1` on GPU.
- no performance losses observed
=> fixed non contiguous error when using lstm_layers > 1 on gpu

darts/models/forecasting/nbeats.py
Fixes https://github.com/unit8co/darts/issues/803.
It fixes wrong seasonality basis vectors generated for NBEATS interpretable model. Now the basis vectors are normalized by the horizon length as it is done in the paper.
--
=> Fix wrong seasonality basis generator for NBEATS

darts/models/forecasting/torch_forecasting_model.py
Fixes #820.
- Removed checkpoint from prediction. We already load the model state when calling `load_from_checkpoint()`, which is why we can remove it from `predict()`
- Updated docs for loading methods as suggested in #814.
=> removed checkpoint from prediction

darts/models/forecasting/block_rnn_model.py, darts/models/forecasting/nbeats.py, darts/models/forecasting/pl_forecasting_module.py, darts/models/forecasting/rnn_model.py, darts/models/forecasting/tcn_model.py, darts/models/forecasting/tft_model.py, darts/models/forecasting/torch_forecasting_model.py, darts/models/forecasting/transformer_model.py
- added train and val loss to progress bar
- changed default `nr_epochs_val_period` from 10 to 1
- updated TorchForecastingModel docs with default values. 
- concerning automatically updating the TFM docs: it is possible with a wrapper around `__init__`. This would then only be visible on the documentation website and not in the source code. I personally like having the docs also in the source code so I left it as is for now.
=> added val loss to progess bar and updated docs

darts/timeseries.py, docs/userguide/gpu_and_tpu_usage.md
Fixes #808 .
As discussed, added a guide on how to use GPU and TPU with PyTorch Lightning. Also shows that a model uses CPU by default, based on an RNN example.
[off-topic] The documentation has a typo in Timeseries [here](https://unit8co.github.io/darts/generated_api/darts.timeseries.html?highlight=timeseries#darts.timeseries.TimeSeries.astype), which I corrected in this pull request.
=> GPU and TPU usage guide

darts/models/forecasting/forecasting_model.py, darts/tests/models/forecasting/test_local_forecasting_models.py
Fixes #843
- fixed wrong RangeIndex-based future covariates slicing for DualCovariatesForecastingModels
- added range index tests for LocalForecastingModels
=> fixed wrong future covariates slicing with RangeIndex

CHANGELOG.md, darts/__init__.py
Fixes #892.
This PR makes it possible to import darts without changing the global matplotlib configuration.
* By default, darts still applies matplotlib configurations
* If the environment variable DARTS_CONFIGURE_MATPLOTLIB=0 is set, then darts.u8plots_mplstyle is still defined but not applied.
Normally it would be best to add tests of the new behavior, but it's difficult to test behavior in the root `__init__.py`.  Both the pre-existing behavior and the adjustment here would be easier to test if the plotting configuration were factored out into some helper module.  That would be a larger (though still fairly small) change.
A larger question would be: _should_ darts change the global matplotlib configuration by default?  Making this opt-in would obviously cause an aesthetic mismatch for …
=> Recognize DARTS_CONFIGURE_MATPLOTLIB=0

darts/models/forecasting/transformer_model.py
No related issue since it's a very minor fix that is easily done.
Corrects the docstring of the `TransformerModel` to make the parameter description match the actual parameter values.
1) the `model` parameter is no longer supported and raises an error when used.
2) `input_chunk_length` and `output_chunk_length` do not have default values.
3) multiple parameters had incorrect default values.
Also fixed some capitalization and punctuation issues and changed "the multiheadattention model" to "the multi-head attention mechanism".
=> Correct the docstring of the TransformerModel

darts/models/filtering/gaussian_process_filter.py
This fixes an error that appeared with latest version of sklearn.
=> Fix array shape

darts/models/forecasting/forecasting_model.py, darts/models/forecasting/torch_forecasting_model.py, darts/tests/models/forecasting/test_TFT.py
Fixes https://github.com/unit8co/darts/issues/764
=> add fit_called checks in global models

darts/models/forecasting/nbeats.py, darts/models/forecasting/nhits.py, darts/tests/models/forecasting/test_nbeats_nhits.py, darts/tests/utils/test_statistics.py
Fixes #.
#954 
Made NHiTs activation configurable between relu and gelu
Apply NHiTs dropout and batch_norm to NBEATs
=> Finish TODOs in NHiTs and NBEATs

darts/models/forecasting/torch_forecasting_model.py
Fixes #991.
- prevents setting `verbose` from overwriting trainer parameters in TorchForecastingModels
=> fixed verbose overwriting trainer parameters

CHANGELOG.md, README.md, setup_u8darts.py
Still to do: update README to mention new features.
=> prepare release 0.20.0

darts/logging.py, darts/models/__init__.py
- no usage of `logger.setLevel` in `darts.logging.get_logger` anymore
- users can use `logging.basicConfig()` before importing darts models to decide whether they want the model warning logs
=> remove logger.setLevel()

docs/userguide/timeseries.md
Signed-off-by: Ryan Russell <git@ryanrussell.org>
Small readability fixes in the TImeSeries user guide.
=> docs: `userguide/timeseries.md` readability improvements

darts/tests/test_timeseries_multivariate.py, darts/timeseries.py
Fixes #880.
Adds a function to drop one or multiple columns to the `TimeSeries`. I tried follow the format and style of the other `TimeSeries` methods and also added a test to the `tests/test_timeseries_multivariate` file (since it does not make sense to drop columns in a single column time series).
=> Adds drop_columns method to TimeSeries

docs/userguide/covariates.md, docs/userguide/forecasting_overview.md, docs/userguide/gpu_and_tpu_usage.md, docs/userguide/torch_forecasting_models.md
Signed-off-by: Ryan Russell <git@ryanrussell.org>
Round 2 on docs readability fixes. Completes `.md` things I noticed.
One thing not included in this PR -- I'm not sure what you are going for on Line 77 of `forecasting_overview.md` with `especially for more expre based models` ... maybe someone internal could touch up that sentence?
Best,
Ryan
=> docs: readability improvements r2

darts/timeseries.py
Fixes #1072 
Renames `ignore_time_axes` to `ignore_time_axis` in TimeSeries.concatenate
=> parameter name change

darts/tests/dataprocessing/transformers/test_missing_values_filler.py, darts/utils/missing_values.py
=> Propagate static covs and hierarchy in missing value filler

darts/timeseries.py
Fixes #1115.
https://github.com/unit8co/darts/blob/caccce1dc71f58180142d96e70bf06024d68798f/darts/timeseries.py#L652
It would be 
> ValueError: If time_col is not specified, the DataFrame must be indexed either witha DatetimeIndex, or with a RangeIndex.
, which `witha` should be `with a`.
None
=> fix typo in timeseries

darts/models/components/transformer.py, darts/models/forecasting/torch_forecasting_model.py, darts/models/forecasting/transformer_model.py, darts/tests/models/forecasting/test_transformer_model.py
Fixes #1116.
- Fixes error when loading TorchForecastingModels where trainer is not associated with a model.
- fixed issue where custom feed forward moduels were ignored in previous PyTorch version
=> reset ptl trainer when loading torch models

CHANGELOG.md, darts/models/forecasting/nbeats.py, darts/models/forecasting/nhits.py, docs/source/userguide.rst
Fixes an issue where num_stacks is used instead of self.num_stacks in the NBEATSModel. Also addresses a few mistakes in API reference docs.
- Corrected mistake in NBEATS model where num_stacks was used iso self.num_stacks
- In the API reference documentation for both N-BEATS and N-HITS it was stated that num_layers is only used if generic _architecture is set to True. This is not the case, it's used all the times for N-BEATS and I believe N-HITS does not have a generic_architecture parameter. This has now been changed.
Fixed an unrelated minor typo somewhere else in the docs
=> #1103 Fixed small issues with N-BEATS and N-HITS 

darts/models/forecasting/block_rnn_model.py, darts/tests/models/forecasting/test_global_forecasting_models.py, examples/04-RNN-examples.ipynb
Issue #651 
Renamed the hidden_size parameter to hidden_dim in BlockRNNModel to match it with RNNModel
=> Issue 651: Renamed hidden_size parameter in BlockRNNModel to hidden_dim

darts/models/forecasting/regression_model.py, darts/tests/models/forecasting/test_regression_models.py, darts/utils/multioutput.py
Addresses #1144 
This PR solves an issue where validation data that was passed to the `LightGBMModel` or the `CatBoostModel` in `fit()` wasn't handled correctly by the original sklearn `MultiOutputRegressor`.
The solution is a slightly modified `MultiOutputRegressor` class that slices the validation data together with the training data.
- Added `MultiOutputRegressor` in `darts.utils.multioutput` that inherits from sklearn `MultiOutputRegressor` and overwrites its `fit()` method
- `MultiOutpuRegressor.fit()` now slices validation data together with training data as long as it is passed in the parameter `eval_set` as part of `**fit_params`
- Added unit tests that check for this case
=> MultiOutputRegressor that handles validation data in fit()

darts/dataprocessing/transformers/reconciliation.py, darts/tests/dataprocessing/transformers/test_reconciliation.py
Fixes https://github.com/unit8co/darts/issues/1035
=> fixed an issue using fit_transform() with reconciliators

darts/timeseries.py
```
FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
from pandas import MultiIndex, Int64Index
```
=> Fix for pandas.Int64Index is deprecated and will be removed from pandas in a future version

CHANGELOG.md, darts/models/forecasting/exponential_smoothing.py
Fixes mistake in type hinting ExponentialSmoothing model
`seasonal: Optional[SeasonalityMode]` iso `seasonal: Optional[ModelMode]`
Potentially useful to add mypy to pipeline and pre-commit hooks?
=> Fix/#1185 corrected type hinting ExponentialSmoothing model

darts/utils/statistics.py
In my last PR it looks like I forgot to add default_formatting to plot_residual_analysis. Below are before and after changes of what this PR enables:
Before:
After:
=> Add the default_formatting parameter to plot_residuals_analysis

darts/models/forecasting/block_rnn_model.py, darts/models/forecasting/catboost_model.py, darts/models/forecasting/gradient_boosted_model.py, darts/models/forecasting/linear_regression_model.py, darts/models/forecasting/nbeats.py, darts/models/forecasting/nhits.py, darts/models/forecasting/random_forest.py, darts/models/forecasting/regression_model.py, darts/models/forecasting/rnn_model.py, darts/models/forecasting/tcn_model.py, darts/models/forecasting/tft_model.py, darts/models/forecasting/torch_forecasting_model.py, darts/models/forecasting/transformer_model.py, darts/tests/explainability/test_shap_explainer.py, darts/tests/models/forecasting/test_covariate_index_generators.py, darts/tests/models/forecasting/test_encoders.py, darts/utils/data/encoder_base.py, darts/utils/data/encoders.py
Fixes the following issues:
- encoder transformer failed when only using a cyclic encoder
- encoder transformer was fit on all series encodings from fit(). This lead to bad results when the series used at predict() do not represent the same series. Now the transformer is globally fit on all observed values per encoded component
- Removed absolute index position encoder and only keep relative index position encoder. Relative basically carries the same information as absolute just that it uses the end of the target series as the reference point. This also makes more sense for transformations, as the maximum value is always 0 when fitting. Users can always implement their own absolute idx logic through the „custom“ encoder (CallableIndexEncoder)
=> Fix encoder transformer and remove absolute index encoder

INSTALL.md
Fixes #1273 .
Add another command in install doc to run docker on m1/m2 machines
=> Fix catboost with docker image on M1/M2

darts/utils/data/tabularization.py
We were reusing the name `idx` of the outer loop in an inner loop. I've fixed it and slightly changed the iterator.
=> Solve an issue reusing an existing name

darts/timeseries.py, datasets/.gitattributes
* Fixes https://github.com/unit8co/darts/issues/1261
* Removes `traffic.csv` from git LFS (I had to do it in this same PR otherwise I couldn't commit)
=> fix deepcopy, remove traffic from lfs

darts/dataprocessing/encoders/__init__.py, darts/models/forecasting/arima.py, darts/models/forecasting/auto_arima.py, darts/models/forecasting/baselines.py, darts/models/forecasting/croston.py, darts/models/forecasting/ensemble_model.py, darts/models/forecasting/exponential_smoothing.py, darts/models/forecasting/fft.py, darts/models/forecasting/forecasting_model.py, darts/models/forecasting/kalman_forecaster.py, darts/models/forecasting/prophet_model.py, darts/models/forecasting/regression_ensemble_model.py, darts/models/forecasting/sf_auto_arima.py, darts/models/forecasting/sf_ets.py, darts/models/forecasting/tbats.py, darts/models/forecasting/theta.py, darts/models/forecasting/varima.py, darts/tests/models/forecasting/test_local_forecasting_models.py, docs/source/conf.py, docs/userguide/forecasting_overview.md
- introduces a dedicted LocalForecastingModel class: no model inherits directly from ForecastingModel anymore -> we can decouple the logic from now on
- renames the local forecasting model base class like DualCovariatesForecastingModel -> FutureCovariatesLocalForecastingModel: I believe we talked once about the naming confusion for this one, and that it should actually be called FutureCovariates... Please correct me if I'm wrong.
-  feel free to propose different class names, or whether I should revert some of the renaming
=> Add dedicated LocalForecastingModel and renaming some model classes

CHANGELOG.md, darts/utils/utils.py, requirements/core.txt
Fixes #1286.
Removes IPython as a core dependency, which makes darts easier to install and maintain in production environments.
=> Remove IPython as a dependency

darts/models/forecasting/pl_forecasting_module.py
Fixes #1341
- fixes passing model output and target values in wrong order to torch metrics
=> fixes torch metrics input order

darts/models/forecasting/forecasting_model.py, darts/tests/models/forecasting/test_backtesting.py
Fixes #1330.
Added the support of a sequence of callable as metric function to be applied to measure the distance between the ground-truth and the prediction during backtesting. The model does not have to be retrained to obtain values for each metric function.
- The backtest function signature remains identical as before to maintain retro-compatibility with existing tests and code.
- This functionality was not extended to the gridsearch method as optimizing several metrics comes with additional challenges and parameters (weighting of the various metric functions for example). However, such feature could be implemented if necessary.
=> backtest can accept a list of callable as metrics functions

darts/tests/test_timeseries.py, darts/timeseries.py
Fixes #1052 and #648. Xarray relies on numpy engine, which is not timezone aware. Causes issues for plotting and resampling.
When constructing a `TimeSeries` from a `pd.DataFrame` or a `pd.Series` with a `DatetimeIndex` containing timezone information, this attribute is dropped without conversion using `tz_localize(None)` (conversion can causes shift in the timestamps, making the index invalid). The timezone information can be recovered by calling `ts.time_index.tz_localize(original_tz)` prior to exporting the data.
The `DatetimeIndex` not used as index are silently converted to UTC by the `pd.DataFrame` constructor without saving the timezone information. Thus, timezone aware dataset should use the time range as index to take advantage of the bugfix and avoid the error raised by the …
=> Make DatetimeIndex timezone naive for compatibility with xarray/numpy engine

darts/tests/test_timeseries.py, darts/timeseries.py
Fixes #1434.
Previously, `append_values` and `prepend_values` did not correctly handle extending `RangeIndex`-typed `TimeSeries`. For example, the following code snippet:
```python
from darts.utils.timeseries_generation import linear_timeseries
import numpy as np
series = linear_timeseries(start=1, length=5, freq=2)
print('Before `append_values`:')
print(list(series.time_index))
new_values = np.ones((1,))
print('After `append_values`:')
print(list(series.append_values(new_values).time_index))
```
would print:
```
Before `append_values`:
[1, 3, 5, 7, 9]
After `append_values`:
[0, 1, 2, 3, 4, 5]
```
This has been fixed in this PR so that this code now prints:
```
Before `append_values`:
[1, 3, 5, 7, 9]
After `append_values`:
[1, 3, 5, 7, 9, 11]
```
Similarly, the code snippet:
```python …
```
=> Fix: `append_values` and `prepend_values` correctly extends `RangeIndex`-typed `TimeSeries`

darts/timeseries.py
Fixes #1444.
- fixes Literal import for python3.7
=> Fix Literal import for python37

darts/tests/dataprocessing/transformers/test_window_transformations.py, darts/tests/test_timeseries.py
Fixes issues arising when running full test suite on Python 3.7. These are issues with the tests mostly, not the library code.
=> Fix a few tests for Py37

darts/models/forecasting/regression_model.py, darts/tests/models/forecasting/test_regression_models.py, darts/timeseries.py, darts/utils/data/tabularization.py
Fixes #1460 
In the original version for the code adding static covariates to regression models, it was assumed that the series are of same length.
This PR corrects this assumption and allows to support  cases where the series in the input sequence have different sizes. 
None
=> Bug fix - correct for multiple lengths of series in input sequence when adding static covariates to regression models

darts/tests/test_timeseries.py, darts/timeseries.py
Fixes https://github.com/unit8co/darts/issues/1480
=> fix issue with slice_n_points on integer indexes

requirements/release.txt
Fixes #1468.
It appears that  a bug associated with `ipython==8.7.0` caused syntax highlighting in the notebook-generated example pages to break - see https://github.com/spatialaudio/nbsphinx/issues/687. Explicitly specifying `ipython==8.8.0` in `requirements/release.txt` seems to solve this problem (at least when I compile the docs locally with `Python 3.10.6`).
=> Fix: Syntax Highlighting in Notebook-Generated Sphinx Pages

darts/timeseries.py
Fixes #1484.
Replace the `Union` return type of `TimeSeries.from_group_dataframe` with a `List["TimeSeries"]`, since the function is guarantied to return a list.
=> Remove unused return type

darts/dataprocessing/encoders/encoder_base.py, darts/tests/models/forecasting/test_regression_models.py
- fixes a bug when using a future covariates encoder with a maximum lag value of 0.
=> fix NoneType error for encoder train index generation

darts/models/forecasting/block_rnn_model.py, darts/models/forecasting/dlinear.py, darts/models/forecasting/nbeats.py, darts/models/forecasting/nhits.py, darts/models/forecasting/nlinear.py, darts/models/forecasting/rnn_model.py, darts/models/forecasting/tcn_model.py, darts/models/forecasting/tft_model.py, darts/models/forecasting/transformer_model.py, docs/userguide/torch_forecasting_models.md
Fixes #1524.
fixes all deprecated references to `save_model()` and `load_model()` to `save()` and `load()`
=> rename all save_modle/load_model to save/load in docu

darts/utils/statistics.py
Fixes #1534.
- fix wrong import 
- add default where missing
- unify format (backticks)
=> fix wrong import and default where missing. unify format (backticks)

darts/ad/anomaly_model/forecasting_am.py
Added a line in the forecasting anomaly model .fit() that removes the none element in the model_fit_kwargs dictionary. 
Further detail about the problem:
"For a forecasting anomaly model, we allow the user to input a parameter model_fit_kwargs (a dictionary that contains the fitting parameter to pass to the fit function of the model). In the code, we add to this dictionary the past_covariates and future_covariates. If the user does not provide the covariates, we still create the keys in the dictionary, but they point to an empty element.
The problem is that not all forecasting models accept past and future covariates (for example, ARIMA does not accept past_covariates). For example, suppose a user creates a forecasting anomaly model with a non-fitted ARIMA model (with …
=> fix model_fit_kwargs by removing none elements

darts/ad/scorers/kmeans_scorer.py, darts/datasets/__init__.py
Fixes Python 3.7 back-compatibility issue introduced by #1502.
- revert lineterminator to line_terminator for `read_csv`
- overwrite the default value of `n_init` with 10 instead of "auto" (sklearn 1.4 changes) to eliminate warning in 3.9 but retain compatibility with 3.7
Sorry for breaking python 3.7.
=> fix: restore Python 3.7 back-compatibility 

darts/models/forecasting/fft.py
Fixes #1587.
`save()` was not working on FTT model if the `trend` argument was neither "poly" or "exp" because the function `lambda x : 0` is not pickable. Just created a class method to have a named function that can be pickled and updated the docstring.
I'll make sure all the other models `save()` method are working before converting this draft PR into a real one.
=> fix: replacing lambda with named function to make model pickable

.pre-commit-config.yaml, darts/dataprocessing/transformers/diff.py
We forgot a docstring entry for the Diff transformer, this PR adds it.
I also had to include one of the changes brought in https://github.com/unit8co/darts/pull/1578/files to make my pre-commit work.
=> add a docstring entry to diff transformer

README.md, examples/12-Dynamic-Time-Warping-example.ipynb
- fixes failing DTW example notebook from renaming MovingAverage to MovingAverageFilter
- corrects README with new MovingAverageFilter name
=> fix failing example notebook from MovingAverage rename

darts/tests/models/forecasting/test_ptl_trainer.py
- fixes failing unit test from #1651 when test env uses older pytorch lightning versions
=> fix failing test when lightning version <2.0.0

darts/timeseries.py
Fixes the type hint introduced in #1592 to make it compatible with python 3.7.
Should fix the failing test on master
=> Fix/Failing test - make TimeSeries.with_hierarchy type hint python 3.7 compatible

README.md, darts/models/forecasting/forecasting_model.py, darts/models/forecasting/varima.py
Fixes #1641
- enforces multivariate input series for VARIMA
- removes univariate support from VARIMA in docs
=> enfore multivariate series for VARIMA

docs/userguide/faq.md, docs/userguide/torch_forecasting_models.md
Fixes #1576  and fixes #1245.
- Update the Torch Forecasting Models [user guide](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html) to better cover the save/load functionalities, notably for training on GPU and inference on CPU.
- Also include some examples of Callbacks : Early stopping and LossLogger, as well as a link to the callbacks implement by PyTorchLightning.
- Add a hint in the FAQ, to help troubleshooting NaNs in the predictions.
The next release is going to break the compatibility with checkpoints obtained with older version of Darts, we should probably start documenting ways to convert them so that user can systematically migrate to the latest versions
=> [DOC] Improve the TFM user guide

examples/01-multi-time-series-and-covariates.ipynb
- Update start value from 0.6 to 0.75 to match the text above the cell.
- Fixing typos
The text above the cell reads: 
> We can also backtest the models using covariates. Say for instance we are interested in evaluating the running accuracy with a horizon of 12 months, starting at 75% of the air series
This commit resolves the issue where the start value was incorrectly set to 0.6 instead of the intended 0.75.
=> Fix/start value for historical_forecasts in examples

darts/models/forecasting/regression_model.py, darts/tests/models/forecasting/test_regression_models.py, darts/utils/multioutput.py
- removes warning when no categorical features are used with new categorical support for LightGBM models (introduced by #1585)
- fixes deprecation warning for joblib Parallel with sklearn.utils.fixes.delayed
=> fixes lgb warning when not using any categorical features

darts/utils/multioutput.py
- fixes failing unittests introduced by #1681. Parallel, delayed were moved from sklearn.utils.fixes to sklearn.utils.parallel in sklearn version 1.3
=> fixes sklearn Parallel issue for sklearn versions < 1.3

darts/dataprocessing/transformers/window_transformer.py, darts/tests/dataprocessing/transformers/test_window_transformations.py, darts/timeseries.py
#1662.
* This improves the documentation such that we explain that the acceptable `window` parameter for an offset is `pandas.Timedelta` data type instead of `pandas.DateOffset`.
* Also add additional test cases for the class `WindowTransformer` to demonstrate the mentioned behaviors.
=> [DOC] Improve the explanation on the window parameter (offset) of WindowTransformer

darts/dataprocessing/transformers/window_transformer.py, darts/tests/dataprocessing/transformers/test_window_transformations.py, darts/timeseries.py
As mentioned in the darts' [gitter chat](https://matrix.to/#/!uumevxjBaNJhovFYgj:gitter.im/$5_mjnsoUNwm3NSisIe_Oggp3Q2191nyQmbmKhQp4rqA?via=gitter.im&via=matrix.org&via=matrix.thegolem.cz), this PR supports a user-defined function name as part of the window transformation output name. 
Without this feature, if we provide multiple user-defined functions for the window operations, we have multiple output names such as `rolling_udf_5_target`, `rolling_udf_5_target_1` and etc. This poses the challenge in tracking the derived feature names.
* Also include an additional test case for window transformation that considers a user-defined function  such as `count_above_mean`.
=> [Feature] Support a user defined function name in the window transformation output

darts/timeseries.py
Fixes #1361 
When a `TimeSeries` method returns an instance of its own class, the annotated return type is changed from `"TimeSeries"` to `typing.Self` (or `typing_extensions.Self` if python_version <= 3.10).
=> Change TimeSeries return type to Self

requirements/core.txt
This PR is an attempt to fix the python=3.10 issues with typing-extensions
=> add typing-extensions as dependency

requirements/core.txt
Fixes failing unit tests with new catboost v1.2.0
=> fix failing unit tests with catboost==1.2.0

darts/models/forecasting/catboost_model.py, darts/models/forecasting/dlinear.py, darts/models/forecasting/lgbm.py, darts/models/forecasting/linear_regression_model.py, darts/models/forecasting/nlinear.py, darts/models/forecasting/random_forest.py, darts/models/forecasting/regression_model.py, darts/models/forecasting/tft_model.py, darts/models/forecasting/xgboost.py
Fixes #.
In some of the docs, we see ([this page](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.lgbm.html))
``predict()`
should be
`predict()`
The reason that this happens is because some of the docstrings missed a `
=> Fix docstring ``predict()` -> ``predict()``

darts/timeseries.py
`pd.Index.is_integer` is deprecated from pandas 2.0. 
This PR replaces `pd.Index.is_integer` with `pd.api.types.is_integer_dtype` in timeseries.py, as advised in the pandas [documentation](https://pandas.pydata.org/docs/reference/api/pandas.Index.is_integer.html)
=> Fix pandas deprecation warning

docs/userguide/hyperparameter_optimization.md
No issue found yet.
Fixes two TypeErrors and one RunTimeError in the Optuna example. This will save new users time troubleshooting the errors. The errors were caused by outdated arguments in `pl_trainer_kwargs` and because Windows needs `if __name__ ==  '__main__':` to run the code properly.
=> Fixed multiple Optuna errors in example

CHANGELOG.md, darts/timeseries.py
This PR changes `TimeSeries.plot()` to be in line with its documentation.
**Example:**
Imagine invoking `plot(label="prediction")` on a `TimeSeries` with the labels `[A, B, C]`.
Before the change, the labels are using an enumeration of the components: `[prediction_0, prediction_1, prediction_2]`.
With the change, the labels are using the component names: `[prediction_A, prediction_B, prediction_C]`.
The change also allows adding a prefix for a series with a single component. This was not possible for some reason.
**Example:**
Imagine invoking `plot(label="prediction")` on a `TimeSeries` with the labels `[A]`.
Before the change, the label would just be ignored: `[A]`.
With the change, the label is taken into account: `[prediction_A]`.
This behaviour is still possible to recreate by calling …
=> Use component names for plotting

examples/00-quickstart.ipynb
Fixes #1792
This pull request fixes the broken documentation link for the LightGBMModel class. It replaces the old link with the correct one.
This is a minor change that does not affect the functionality of the library.
=> Fix broken link in 00-quickstart.ipynb

darts/datasets/__init__.py
Updated the link to the Electricity Dataset (ElectricityLoadDiagrams20112014 on UC Irvine ML Repository), the hash did not change.
Old link leads to 404 error.
=> Fix link to Electricity Dataset

CHANGELOG.md, darts/dataprocessing/transformers/static_covariates_transformer.py
Fixes #1862 .
changed category mappings such that static covariate components now are of the form `<original_column_name>_<value1>`, `<original_column_name>_<value2>`, instead of `<value1>`, `<value2>`. To account for cases where you have one category that is used by two (or more) static covariates. E.g. temperature could be low/medium/high, and sun_hours could be low/medium/high.
=> 1862 more robust way of component naming

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/merge.yml, CHANGELOG.md, INSTALL.md, README.md, conda_recipe/environment.yml, darts/tests/dataprocessing/transformers/test_window_transformations.py, darts/tests/models/forecasting/test_regression_models.py, setup.py, setup_u8darts.py
- drops python 3.7 support due to [End Of Life](https://endoflife.date/python)
=> bump minimum python version from 3.7 to 3.8

CHANGELOG.md, darts/tests/test_timeseries.py, darts/timeseries.py
- fixes TimeSeries `__getitem__` with series that have a RangeIndex with start != 0 and freq != 1.
- adds unit test for getitem of integer indexed series
=> fix getitem with rangeindex start != 0 and freq != 1

darts/datasets/__init__.py
Fixes None.
The argument has been [renamed](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html).
=> Fix deprecation warning

CHANGELOG.md, darts/models/forecasting/arima.py
Fixes #1892
- fixes anchor for ARIMA simulation (probabilistic forecasting) from start to end to properly use future covariates
=> anchor ARIMAS simulation to end of series

requirements/core.txt
- fixes xarray issues for python<3.9 and pandas>=2.0.0. Caps pandas at <=2.0.0 when installing from python38
=> cap pandas for python<3.9

darts/models/forecasting/baselines.py
fix failing unit tests that is importing torch at core requirements level
=> fix failing tests by avoiding to import torch in baseline models

darts/models/forecasting/ensemble_model.py
Part 2 for fixing failing unit tests due to likelihood import at core level requirements (in darts/models/forecasting/ensemble_model.py)
=> remove likelihood import from ensemble_model due to torch flavor

darts/explainability/shap_explainer.py, darts/models/forecasting/pl_forecasting_module.py, darts/models/forecasting/torch_forecasting_model.py, darts/tests/explainability/test_tft_explainer.py, darts/tests/test_timeseries.py, darts/tests/utils/test_statistics.py, darts/timeseries.py, darts/utils/historical_forecasts/optimized_historical_forecasts.py, darts/utils/statistics.py
Solving various warning messages appearing when running the unit-tests:
- removed deprecated `loffset` argument of `xarray.resample`, used by `TimeSeries.resample`.
- removed deprecated `verbose` argument of `granger_stationarity_test`
- `loss_fn` and `metrics` attributes of `TorchForecastingModels` checkpointing is handled in `on_save/on_load_checkpoints` and ignored in the constructor call to `save_hyperparameters`
- target series is passed to `create_lagged_prediction_data` only when the corresponding lags are defined (optimized historical forecast and shap explainer)
- closing matplotlib figures created in `TFTExplainer` unit-tests
Majority of remaining warnings are caused by statsforecast (ill-conditioned matrix, failure to converge, ...) or p-values outside of the tables that would …
=> Solve some warnings triggered in unittests

darts/tests/models/forecasting/test_probabilistic_models.py
fixes failing unittest from TorchForecastingModel import in core tests.
=> fix torch import

CHANGELOG.md, build.gradle, darts/tests/test_timeseries.py, darts/timeseries.py
Fixes #1522.
xarray constructor raise an error when the `Index` containing the name of the columns has a `name` (which not necessarily the name of the index itself, even if it can be displayed as such). Simply setting this name to `None` solve the problem without impacting the attributes of the generated `TimeSeries`.
=> fix: remove dataframe.columns name to avoid error with xarray

darts/explainability/tft_explainer.py
In tft_explainer it imports shap instead of tft, nothing crazy
=> Fix tft_explainer to import right module

darts/timeseries.py
In a command line the missing space gives us the word "contiguousin" instead of "contiguous in".  Added said space.
You all rule.
=> Added space so we have "contiguous in" and not "contiguousin".

darts/tests/models/forecasting/test_probabilistic_models.py
- Patch release of pytorch lightning 2.0.8 slightly changed the performance of the deep-learning based models, making the unittest failing for `TiDEModel`. Updated the expected value accordingly
- Separated the univariate and multivariate probabilistic forecasts tests using the `supports_multivariate` attribute, allowing for more granularity in the expected error (for facilitating the detection of other performance decrease in the future).
=> Fix/Updated tests with patch release 2.0.8 of PL

examples/01-multi-time-series-and-covariates.ipynb
fix 2 typos in docs:
https://unit8co.github.io/darts/examples/01-multi-time-series-and-covariates.html
At the end, this page has typos:
> sequence of serie, 
> the model used actually support them
=> fix typo in documentation

darts/tests/models/forecasting/test_regression_models.py
Force `tree_method='exact'` in the unittests as the default value changed to `'hist'` (which was resulting in slightly worse performance in the tests).
[Link](https://github.com/dmlc/xgboost/releases) to the full changelog.
=> Fix/Updated tests with release 2.0.0 of XGBoost

CHANGELOG.md, darts/models/forecasting/tide_model.py, darts/tests/models/forecasting/test_tide_model.py
Adds feature projection for past covariates to TiDEModel
After a discussion with the architect of TiDEModel, we adapt the past covariates handling by using a feature project as done for the future covariates.
As a reference, the discussion on Gitter can be found [here](https://matrix.to/#/!uumevxjBaNJhovFYgj:gitter.im/$OXXTBmWLKAc89xb9VHEPWafRUBejQ9eMyb2xU0WbN7Y?via=gitter.im&via=matrix.org&via=matrix.freyachat.eu).
=> add feature projection for past covariates to TiDEModel

darts/models/forecasting/fft.py, darts/models/forecasting/linear_regression_model.py, darts/models/forecasting/torch_forecasting_model.py, darts/models/forecasting/xgboost.py
It previously looked like this:
How can we check that it is now better?
=> Fix doc formatting of LinearRegressionModel

darts/utils/statistics.py
It previously looked like this (where the "Returns" section is broken):
=> Fix doc rendering in statistics.py

CHANGELOG.md, darts/models/forecasting/xgboost.py
Fixes #1669
- Leverage built-in Quantile Regression for XGBoost versions >= 2.0.0 to improve accuracy
- XGBoost supports multi quantile regression which we do not levarage yet. Instead, we train a separate model per quantile to use the same logic as with LightGBM. We can change this in the future
Comparison Quantile Regression with XGBoost < 2.0.0 (top) and XGBoost >= 2.0.0 (bottom)
=> Native quantile regression for xgb 2.0.0 and above

CHANGELOG.md, darts/models/forecasting/torch_forecasting_model.py, darts/tests/models/forecasting/test_torch_forecasting_model.py
Fix bug for TorchForecastingModel calling load_weights with float16 and float32. Fixes #1987.
- Train the TorchForecastingModel with **float32** following the [instruction](https://unit8co.github.io/darts/userguide/torch_forecasting_models.html#build-your-timeseries-using-32-bits-data) and `.save` it to disk.
- Create a new model instance and call `.load_weights` to restore it.
- The `mock_train_sample` in `.load_weights_from_checkpoint` built from `np.zero` without specifying the `dtype`, so it sticks to the default **float64**, and causes the `self.train_sample` stays **float64**, too.
=> fix: torch_forecasting_model load_weights with float16 and float32

darts/datasets/__init__.py
- fixes electricity zurich dataset for python 3.8
=> fix dataset for python38

CHANGELOG.md, darts/models/forecasting/dlinear.py, darts/models/forecasting/nlinear.py, darts/tests/models/forecasting/test_global_forecasting_models.py, darts/tests/models/forecasting/test_torch_forecasting_model.py
Fixes #2036.
- The assumption on the static covariates dimensions was not accounting for the two possible representation/encoding of the static covariates in multivariate series : either shared across components `shape = (1, nb_static_covs)` or component-specific `shape = (nb_components, nb_static_covs)`
- Added corresponding test for the torch models accepting `use_static_covariates=True`
- Added missing type hint in both `DLinearModel` and `NLinearModel`
- Fixed small typo in the warning message when torch in not installed
=> Fix/dlinear and nlinear use_static_cov. with multivariate series

examples/20-RegressionModel-examples.ipynb
Fixes #2094.
Fixes the formula in the description of the single-shot forecast in the `examples/20-RegressionModel-examples.ipynb` example notebook.
=> Fix formula in example notebook #20 (single-shot vs. auto-regressive forecasting)

darts/models/forecasting/block_rnn_model.py, darts/models/forecasting/pl_forecasting_module.py, darts/models/forecasting/rnn_model.py, docs/Makefile, docs/generated_api/darts.models.forecasting.block_rnn_model.rst, docs/generated_api/darts.models.forecasting.rnn_model.rst, docs/templates/module.rst_t
Adds custom .rst files for RNN and BlockRNNModules to avoid generating the docs from PLForecastingModule for Custom Modules.
- Makefile auto generates documentation for all modules using the templates defined in `docs/templates`
- Added a new folder `docs/generated_api` for custom .rst files for the generated API. All files in this folder will be copy pasted into the the auto-generated folder `docs/source/generated_api`.
=> exclude PLForecastingModule docs from custom rnn and blockrnn modules

darts/tests/test_timeseries.py, darts/tests/test_timeseries_static_covariates.py, darts/timeseries.py
Fixes #2101.
In this new version of the `TimeSeries.pd_series` method, the newly created `Panda.Series` instance to be returned takes as its name the one from the `TimeSeries` object (stored as the first item in the iterable attribute `self.components`).
This new version of the `TimeSeries.pd_series` method returns a new `Pandas.Series` instance with the name of the original `TimeSeries` object (`series`).
```
>>> import pandas as pd
>>> from darts.timeseries import TimeSeries
>>> idx = pd.date_range("2018-01-01", periods=5, freq="D")
>>> ts = pd.Series(range(len(idx)), index=idx, name="series_name")
>>> ts
2018-01-01    0
2018-01-02    1
2018-01-03    2
2018-01-04    3
2018-01-05    4
Freq: D, Name: series_name, dtype: int64
>>> series = TimeSeries.from_series(ts)
>>> series.pd_series() …
```
=> fix TimeSeries.pd_series not retaining original name

examples/19-EnsembleModel-examples.ipynb
In `19-EnsembleModel-examples.ipynb`: Falman -> Kalman
=> Fix typo in examples Ensemble Model

requirements/torch.txt
see #2133
- fixes currently failing unit tests
- sets an upper cap on pytorch lightning <=2.1.2 to fix the checkpoint symlink issue.
- pytorch lightning already reverted these changes [here](https://github.com/Lightning-AI/pytorch-lightning/pull/19191). Will relax the cap once they release the new version
=> upper cap pytorch lightning for ckpt symlink fix

CHANGELOG.md, darts/models/forecasting/pl_forecasting_module.py
Fixes #2159.
Now, the `io_processor` wrapper doesn't clone tensor before applying `.rin` to it, which leads to overwriting initial input tensor and to incorrect results during the `.predict` method. By applying .clone() to the `args[0][0]` inside `io_processor`, we can prevent such behavior.
To reproduce previous and current behavior you can use the following snippet:
```python
from functools import wraps
import torch
from darts.models import NBEATSModel
from darts.models.forecasting.nbeats import _NBEATSModule
from darts.timeseries import TimeSeries
from typing import Tuple
class Counter:
def __init__(self):
self.value = 0
def incr(self):
self.value += 1
def reset(self):
self.value = 0
LEAK_COUNTER = Counter()
SAFE_COUNTER = Counter()
def io_processor(forward):
@wraps(forward)
def …
```
=> Fix: removed input re-normalization by rin inside `io_processor`

darts/tests/models/forecasting/test_torch_forecasting_model.py, requirements/release.txt
- fixes currently failing release tests in merge workflow. Bump shinx from  4.3.2 to v5.0.0
- tested new docs build, everything looks fine
- fixed some failing TFM unit tests when running on M1
=> sphinx sphinx release workflow issue

CHANGELOG.md, darts/tests/test_timeseries.py, darts/timeseries.py
Fixes #2089 .
Currently when indexing a `TimeSeries`, the frequency of the new `TimeSeries` is inferred from dates of the new `TimeSeries`.
However, we often have information to do a more correct inference, in particular in the following cases:
- The `__getitem__` argument is a `pd.DatetimeIndex` with a set `.freq` attribute
- We index with a slice 
This PR contains the following improvements to frequency inference in the `TimeSeries.__getitem__` method:
- When a `pd.DatetimeIndex` with a set `.freq` attribute is used as `__getitem__` argument, we use this attribute as the new `TimeSeries` frequency
- When a `slice` without `step` parameter is used as `__getitem__` argument, the original `TimeSeries` frequency is used
- When a `slice` with `step` parameter is used as `__getitem__` …
=> Fix: Improve TimeSeries.__getitem__ frequency inference

darts/utils/multioutput.py
- fixes failing unit tests due to new sklearn v1.4.0: method `_check_fit_params` was renamed to `_check_method_params`
=> fix deprecated method import from sklearn==1.4.0

.gitignore
Ignores files such as the following, which get created by coverage measurement tools:
```
.coverage.68a13e4de0d0.43514.XMNYGdrx
.coverage.68a13e4de0d0.43515.XjbvzNqx
```
=> Update .gitignore to ignore intermediate coverage files

darts/dataprocessing/transformers/midas.py
- fixes last failing unit tests for py38 due to pandas version 2.2.0
=> fix wrong pandas freqstr for py38

CHANGELOG.md, darts/metrics/metrics.py
Fixes #2157.
- use `_get_values_or_raise` in `coefficient_of_variation` to have the appropriate denominator when `intersect = True`
=> fix: time index intersection for coefficient of variation

CHANGELOG.md, darts/models/forecasting/linear_regression_model.py, darts/models/forecasting/regression_ensemble_model.py, darts/models/forecasting/regression_model.py, darts/tests/models/forecasting/test_regression_ensemble_model.py
Fixes #2200.
- prevent creation of RegressionEnsemble with a `regression_model` with `multi_models=False` as it would require additional forecasts (and potentially auto-regression) from the `forecasting_models` when calling `predict()`.
- overwrite the `model` attribute of probabilistic `LinearRegressionModel` with the sub-models containers to make the access of the coefficients more intuitive
=> Fix/RegressionEnsemble with single model regressor and coef access in LinearRegressionModel

CHANGELOG.md, darts/models/forecasting/pl_forecasting_module.py, darts/tests/models/forecasting/test_torch_forecasting_model.py
Adds support for more lr scheduler configuration parameters to TorchForecastingModels:
- "interval": "epoch" (The unit of the scheduler's step size, could also be 'step'.
'epoch' updates the scheduler on epoch end whereas 'step'
updates it after a optimizer update)
- "frequency": 1 (How many epochs/steps should pass between calls to
`scheduler.step()`. 1 corresponds to updating the learning
rate after every epoch/step.)
- "monitor": "val_loss" (Metric to to monitor for schedulers like `ReduceLROnPlateau`)
- "strict": True (If set to `True`, will enforce that the value specified 'monitor'
is available when the scheduler is updated, thus stopping
training if not found. If set to `False`, it will only produce a warning)
- "name": None (If using the `LearningRateMonitor` callback to monitor …
=> add support for more lr scheduler config parameters to torch models

.pre-commit-config.yaml, CHANGELOG.md
Update pre-commit hooks to their latest version.
it originated with a bug with flake8 hook on my computer that didn't want to run. The upgrade fixed it.
=> Pre commit hooks upgrade

CHANGELOG.md, darts/dataprocessing/transformers/window_transformer.py, darts/tests/dataprocessing/transformers/test_window_transformations.py, darts/timeseries.py
Fixes #2204, fixes #2209.
- If `window_transform()` is called with only one transform on all the components of the series, update the hierarchy with the new components names, otherwise, it's dropped.
=> fix: update hierarchy for single transform window_transform

darts/datasets/__init__.py
- pandas v2.2.0. introduced a bug which resulted in a different hash for the ElectricityConsumptionZurich dataset
- the bug was fixed in v2.2.1, and we can use the original hash again
=> fix ElectricityConsumptionZurich dataset hash

darts/tests/datasets/test_datasets.py
- fixes failing dataset unit tests for python 3.8, where `inspect.signature` did not yet access the `cls.__init__()` method directly
=> fix failing dataset unit tests for py38

CHANGELOG.md, darts/models/__init__.py, darts/tests/models/forecasting/test_probabilistic_models.py
Fixes a segmentation fault when important LightGBMModel.
- Some Mac users faced segmentation faults when importing `LightGBMModel`. For some reason importing `lightgbm` at the wrong place (relative to other dependency imports) can cause this segmentation fault. A fix for this was to import `lightgbm` at the top in the module/script where the model was used.  
- To fix this generally in `Darts`, I moved the `LightGBMModel` import to the top of `darts/models/__init__.py` (see also https://github.com/shap/shap/issues/3092 which had a similar issue).
=> fix lighgbm segmentation fault

darts/tests/datasets/test_datasets.py, darts/tests/explainability/test_tft_explainer.py, darts/tests/models/components/glu_variants.py, darts/tests/models/components/test_layer_norm_variants.py, darts/tests/models/forecasting/test_RNN.py, darts/tests/models/forecasting/test_TCN.py, darts/tests/models/forecasting/test_TFT.py, darts/tests/models/forecasting/test_block_RNN.py, darts/tests/models/forecasting/test_dlinear_nlinear.py, darts/tests/models/forecasting/test_global_forecasting_models.py, darts/tests/models/forecasting/test_nbeats_nhits.py, darts/tests/models/forecasting/test_ptl_trainer.py, darts/tests/models/forecasting/test_tide_model.py, darts/tests/models/forecasting/test_torch_forecasting_model.py, darts/tests/models/forecasting/test_transformer_model.py, darts/tests/models/forecasting/test_tsmixer.py, darts/tests/utils/test_likelihood_models.py, darts/tests/utils/test_losses.py, darts/tests/utils/test_utils_torch.py, docs/source/examples.rst, examples/21-TSMixer-examples.ipynb
- not required
- uses pytest to skip torch tests at module level rather than defining tests under if/else scope
=> use pytest to skip torch tests

.pre-commit-config.yaml, CHANGELOG.md, requirements/dev.txt
- bumps `black` from 24.1.1 to 24.3.0 to fix vulnerability with versions <24.3.0. See [here](https://github.com/unit8co/darts/security/dependabot/5)
=> bump black[jupyter] 24.1.1 to 24.3.0

.github/workflows/develop.yml, .github/workflows/merge.yml, CHANGELOG.md
- Fixes failing CI pipeline at Codecov upload step. 
- Codecov was added to Github apps since Access tokens (classic) have been disabled
- Added codecov token secret to repository
- CI now uses that token to authenticate
=> add codecov token to merge and dev ci pipelines

darts/tests/models/forecasting/test_regression_models.py
- reduces regression model test computation time from **6 min 20 seconds down to 34 second**s by using a light version of gradient boosted trees
- one drawback is that for gradient boosted models, the expected errors are higher, since we don't allow them to learn. However, I'm not sure that we really need to test the forecasting accuracy for these models.
=> speed up regression model tests

CHANGELOG.md, darts/models/forecasting/regression_model.py, darts/utils/historical_forecasts/optimized_historical_forecasts_regression.py
Fixes #2061.
- Added a progress bar when performing optimized historical forecasts (`retrain=False` and no autoregression) to display the series-level progress.
- can be activated with `verbose=True` when calling `ForecastingModel.historical forecasts()`
=> add progress bar to regression models for hist fc

CHANGELOG.md, darts/tests/utils/test_utils.py, darts/timeseries.py, darts/utils/utils.py
Fixes #2352.
- fixes a bug where `n_steps_between` did not work properly with custom business frequencies
- fixes a bug where `generate_index()` with a negative frequencies and either `start` or `end` not intersecting with the frequency, did not return the correct index.
- fixes other edge cases with `generate_index()` and `n_steps_between`
=> fix index generation and n steps between

darts/tests/test_timeseries.py, darts/tests/utils/test_timeseries_generation.py
- fixes failing unit tests for py38 due to wrong frequency aliases
=> fix failing unit tests

darts/models/forecasting/tsmixer_model.py
Fixes #2372 .
- corrects docstring for `TSMixer` model creation parameters `loss_fn` and `likelihood`
=> fix tsmixer loss_fn/likelihood param docs

CHANGELOG.md, darts/models/forecasting/pl_forecasting_module.py, darts/tests/models/forecasting/test_torch_forecasting_model.py
Fixes #2390, fixes #2389
Instead of doing forward/log on metrics on each step it only updates the state at every step and does the computation/log/reset at the end of the epoch.
=> rework metrics logic to support states

CHANGELOG.md, darts/models/forecasting/torch_forecasting_model.py, darts/tests/models/forecasting/test_torch_forecasting_model.py
Add `torch.utils.data.DataLoader` related parameters to `fit()` and `predict()` of `TorchForecastingModel`
=> add `DataLoader` related parameters to `fit()` and `predict()`

CHANGELOG.md, requirements/core.txt, requirements/release.txt
Numpy released version 2.0.0. This broke a lot of our dependencies. Until they have migrated, we set an upper cap. 
- fixes failing CI pipeline due to `numpy==2.0.0` and `tenacity==8.4.0`
- sets upper caps `numpy<2.0.0` and `tenacity<=8.3.0`
- we'll monitor the dependencies until we can migrate as well
=> upper cap numpy<2.0.0

darts/tests/test_timeseries.py
Contributes to #2435
Fixes #.
Replacing `DataFrame.applymap` to `DataFrame.map`.
Removes the warning:
`FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.`
Replacing the obsolete applymap with map
=> Replacing the obsolete applymap with map

darts/datasets/__init__.py
Fixes #2325 
Need checking for older versions of pandas.
FutureWarning:` Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.`
Fixes #2325 
Replacement of deprecated Series.fillna -> 'method' with ffill() and bfill().
=> Replacement of deprecated Series.fillna -> 'method' with ffill() and bfill()

CHANGELOG.md, darts/models/forecasting/regression_model.py, darts/tests/models/forecasting/test_regression_models.py, darts/utils/multioutput.py
Fixes #2439.
fixes the sample_weights bug by making conditional judgement on whether sample_weights is none and whether the parameter sample_weights exists in the model fit method.
=> fix the sample_weights bug

darts/tests/metrics/test_metrics.py
Fixes #.
Removes warning:
```
darts/tests/metrics/test_metrics.py:88
/home/runner/work/darts/darts/darts/tests/metrics/test_metrics.py:88: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
pd_series1[:] = pd_series1.mean()
```
Setting in `pd_series1[:] `with type `int64` to `pd_series1.mean()` with type `float64` causes a warning. 
The average itself implies a float value. To avoid this, pd_series1 is converted to float64.
=> Convert pd_series1 to float64 type

darts/timeseries.py
- fixes currently failing unit tests when using `TimeSeries.reample()` with a freq of type `pandas.DateOffset`
=> fix resampling with DateOffset

darts/tests/test_timeseries.py
I didn't open an issue for this tiny change because it's so small and internal to the tests.
Hope that's okay; will of course open issues for anything substantial.
Minor fix to actually use `pd_series3` for `series3` in `test_timeseries.py` (instead of `pd_series2`).
Luckily only one test needed to be adjusted for everything to pass.
No entry in changelog because it's a negligible and internal change.
I read the contribution guidelines but it's my first contribution to Darts nonetheless, so I am more than happy to get notes or feedback :)
=> Minor fix: Use pd_series3 for series3 in tests

CHANGELOG.md, darts/tests/test_timeseries.py, darts/timeseries.py
Fixes #2475
Allows broadcasting TimeSeries with a single sample onto TimeSeries with multiple samples for element-wise operations like addition, subtraction, etc. Note that the underlying implementation already supports broadcasting, this PR only relaxes the safeguard regarding the shape-compatibility when combining two TimeSeries. Depending on the other uses of the `_combine_arrays` method, there could also be an argument that allows broadcasting like this but given that I don't know the code base well enough to judge that, I implemented the simpler version (and made sure that all the tests still pass).
This PR is a draft because it's still up for discussion what other types of broadcasting might be interesting to allow.
I read the contribution …
=> Allow broadcasting single-sample TimeSeries onto multi-sample TimeSeries

CHANGELOG.md, darts/models/forecasting/regression_model.py, darts/tests/models/forecasting/test_probabilistic_models.py
- Fixes a bug when predicting with `predict_likelihood_parameters=True`, `n > 1` and a `RegressionModel` with `multi_models=False` that uses a `likelihood`. The prediction now works without raising an exception.
=> fix plkl param prediction with multi_models=False

darts/models/forecasting/pl_forecasting_module.py, darts/tests/models/forecasting/test_torch_forecasting_model.py
- fixes failing unit tests for torch metrics for multivariate forecasting (since torchmetrics [v1.5.0](https://lightning.ai/docs/torchmetrics/stable/generated/CHANGELOG.html#id2))
=> fix failing torch test for torchmetrics when multi output

CHANGELOG.md, darts/tests/utils/tabularization/test_create_lagged_training_data.py, darts/utils/data/tabularization.py
Fixes #2574.
- Fixes a bug when using `darts.utils.data.tabularization.create_lagged_component_names()` with target `lags=None`, that did not return any lagged target label component names.
=> fix bug in create lagged component names without target lags

examples/02-data-processing.ipynb
=> minor spell fix

darts/tests/utils/historical_forecasts/test_historical_forecasts.py
Fixes failing historical forecasts tests from missing torch dependency.
=> fix failing hist fc tests from missing torch

CHANGELOG.md, darts/utils/historical_forecasts/optimized_historical_forecasts_regression.py
- fixes bug when performing optimized historical forecasts with `RegressionModel` and `last_points_only=False`, where the forecast index generation could result in out-of-bound dates.
=> fix index generation for optimized hist fc with regression models

README.md, darts/models/forecasting/conformal_models.py, darts/tests/models/forecasting/test_conformal_model.py
- fixes bug where encoders were not properly called in conformal models
=> fix encoder support for conformal models

CHANGELOG.md, darts/models/forecasting/regression_model.py, darts/tests/models/forecasting/test_regression_models.py
Fixes [#2652](https://github.com/unit8co/darts/issues/2652#issue-2807058011)
- When initiating a `RegressionModel` with `lags_past_covariates` as dict and `lags_future_covariates` as some other type (not dict) and `output_chunk_shift>0`, an error occurred. 
- This was because `lags_future_covariate` is not a component lag and should therefore not be handled at any point by `processed_component_lags`.
- Adjusting the `if` statement in line 396 of `regression_model.py` fixes the bug.
None
=> fix lags_past_covariates dict type breaks lags_future_covariates when output_chunk_shift>0

darts/models/forecasting/torch_forecasting_model.py
Fixes failing TorchForecastingModel load methods from pytorch>=2.6.0.
PyTorch changed the default value of `weights_only` from `False` to `True`.
=> fix failing tfm load with pytorch>=2.6.0

CHANGELOG.md, darts/models/forecasting/global_baseline_models.py, darts/tests/models/forecasting/test_baseline_models.py, darts/tests/models/forecasting/test_global_forecasting_models.py
Fixes an issue mentioned on gitter where Global Naive models could not be used in ensemble models.
Code to reproduce below.
- Fixed a bug where global naive models could not be used in ensemble models
- Fixed a bug with global naive models where some `supports_*` properties were wrongly defined as methods.
Code to reproduce the issue:
```
import numpy as np
from darts.datasets import AirPassengersDataset
from darts.models import NaiveEnsembleModel, GlobalNaiveDrift
series = AirPassengersDataset().load().astype(np.float32)
model = NaiveEnsembleModel(
forecasting_models=[
GlobalNaiveDrift(input_chunk_length=12, output_chunk_length=12).fit(series)
],
train_forecasting_models=False,
)
pred_kwargs = {"predict_likelihood_parameters": True, "verbose": True} …
```
=> Fix global naive models cannot be used in ensemble models

CHANGELOG.md, darts/models/forecasting/forecasting_model.py, docs/source/conf.py
Fixes #2677 
Public function `ForecastingModel.untrained_model()` is no in docs
=> add public function untrained_model() in docs

CHANGELOG.md, darts/models/forecasting/torch_forecasting_model.py
Fixes #2687, fixes #2681
- fixes errors when loading a torch model that was trained on another device, than the one that is loaded on
- revert back to saving / loading the TFM wrapper with torch rather than pickle
=> revert back to saving and loading a TFM with torch rather than pickle

CHANGELOG.md, darts/tests/test_timeseries.py, darts/timeseries.py, examples/05-TCN-examples.ipynb, examples/07-NBEATS-examples.ipynb, examples/08-DeepAR-examples.ipynb, examples/09-DeepTCN-examples.ipynb, examples/21-TSMixer-examples.ipynb
- 🔴 Removed deprecated method `TimeSeries.pd_dataframe()`.
- 🔴 Removed deprecated method `TimeSeries.pd_serise()`.
=> Remove deprecated `pd_dataframe()` and `pd_series()`

CHANGELOG.md, darts/models/forecasting/pl_forecasting_module.py, darts/tests/models/forecasting/test_torch_forecasting_model.py
Fixes #2785.
Reshape the pred and target regardless of whether `self.n_targets > 1`, to satisfy some torch_metrics such as R2Score(`preds.ndim <= 2`)
=> Fix the torch_metric shape error

CHANGELOG.md, darts/models/forecasting/conformal_models.py, darts/models/forecasting/pl_forecasting_module.py, darts/models/forecasting/sf_model.py, darts/models/forecasting/sklearn_model.py, darts/models/forecasting/torch_forecasting_model.py, darts/tests/test_timeseries.py, darts/tests/utils/test_likelihood_models/test_likelihoods.py, darts/tests/utils/test_likelihood_models/test_torch_likelihoods.py, darts/tests/utils/test_timeseries_generation.py, darts/tests/utils/torch_datasets/test_torch_datasets.py, darts/timeseries.py, darts/utils/data/torch_datasets/inference_dataset.py, darts/utils/data/torch_datasets/utils.py, darts/utils/historical_forecasts/optimized_historical_forecasts_regression.py, darts/utils/historical_forecasts/optimized_historical_forecasts_torch.py, darts/utils/likelihood_models/base.py, darts/utils/timeseries_generation.py
Fixes #2780.
- Drastically improves prediction efficiency of `TorchForecastingModel`.
- Moved forecast TimeSeries creation out of the batch prediction process and instead apply it once on the total predictions. Using multi-processing (`n_jobs>1`) created a huge overhead when performing it on the batch-level
- Using multi-processing (`n_jobs>1`) now boosts the forecast `TimeSeries` creation proportionally!
- Instead of passing the entire `TimeSeries` as part of the prediction batches, we now only pass the schema of the `TimeSeries`.
- Added parameter `values_only: bool = True` to `TorchForecastingModel.predict_from_dataset()`:
- Whether to return the predicted values only. If `False`, will return `TimeSeries` objects. Otherwise, will
return a tuple of …
=> Improve TorchForecastingModel prediction efficiency

CHANGELOG.md, darts/models/forecasting/sklearn_model.py, darts/tests/models/forecasting/test_sklearn_models.py, darts/utils/multioutput.py
Fixes #2810.
Fixes a bug with `SKLearnModel.__str__()` which raised an error when the model was wrapped by Darts' MultioutputRegressor.
=> Fix SKLearn Multioutput string representation

CHANGELOG.md, darts/explainability/shap_explainer.py
I noticed that retrieving shapley values for certain tree-based models (e.g., `ExtraTreeRegressor`) took significantly longer when the `shap_method` argument was not specified explicitly. When this argument is unspecified a mapping based on the underlying ML model happens in the background. I noticed there that the `ExtraTreeRegressor` and `RandomForestRegressor` mapped to the permutation method rather than the (faster and hence more applicable default) tree method. Notice that the `ExtraTreeRegressor`  model in fact had 2 entries in the dict (one mapping to the tree method and one mapping to permutation). Due to the sequence this will always evaluate to permutation.
This PR changes the default for both models to `_ShapMethod.TREE`
=> fix: change default shap method of extra trees and random forest models

CHANGELOG.md, darts/models/forecasting/sf_model.py
Fixes #2823.
- Fixes bug in StatsForecastModel where custom future covariates support (OLS) resulted in a feature error with target series that contain static covariates.
=> Ignore static covs for OLS with custom future covariates support in SF models

CHANGELOG.md, darts/tests/utils/test_timeseries_generation.py, darts/utils/timeseries_generation.py
- Fixed a bug in `darts.utils.timeseries_generation.sine_timeseries()`, where the returned series ignored the specified `dtype`.
=> Fix dtype for sine_timeseries

.github/workflows/develop.yml, .github/workflows/doc.yml, .github/workflows/merge.yml, .github/workflows/release.yml, darts/tests/models/forecasting/test_torch_forecasting_model.py
- Avoids installing darts locally in gh actions workflows for running unit tests. Before, installing locally caused torch dependencies to be installed as well, and the notorch flavor tests did not properly catch issues on missing torch installations.
=> update gh action workflow to install darts locally without dependencies

CHANGELOG.md, darts/models/forecasting/prophet_model.py, darts/tests/models/forecasting/test_prophet.py
Fixes #2878.
This PR introduces a new parameter, `add_regressor_configs`, to the `DartsProphet` model to allow for per-regressor configurations.
Currently, all future regressors added to the Prophet model use the same default parameters. This change addresses that limitation by allowing users to specify individual settings for `prior_scale`, `mode`, and `standardize` for each regressor. This provides much greater flexibility and control over the model, which is especially useful when users have domain knowledge about the influence of different external variables.
The implementation follows the suggestion in issue #2878, using a dictionary of configurations that are unpacked during the `_fit` process. The change is fully backward-compatible and does not affect existing functionality. New …
=> feat: Add add_regressor_configs to Prophet model
